import { PrismaClient } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.join(__dirname, '../.env') });
dotenv.config({ path: path.join(__dirname, '../.env.local'), override: true });

const prisma = new PrismaClient({ log: ['warn', 'error'] });

const RECIPES = [
  {
    slug: 'classic-party-jollof-rice',
    title: 'Classic Party Jollof Rice',
    heroImage: '/recipes/classic-party-jollof-rice.jpg',
    cookTimeMin: 65,
    servings: 8,
    category: 'Nigerian',
    difficulty: 'Medium',
    description: 'The ultimate West African party dish — smoky, deeply spiced rice cooked in a rich blended tomato and pepper stew. The secret is that final burn on the bottom.',
    ingredients: [
      { name: 'Long Grain Parboiled Rice', quantityText: '3 cups', sku: 'CAPRICE-RICE' },
      { name: 'Plum Tomatoes (canned)', quantityText: '1 can (400g)' },
      { name: 'Red Bell Peppers (Tatashe)', quantityText: '3 large' },
      { name: 'Scotch Bonnet Peppers', quantityText: '2 (adjust to taste)' },
      { name: 'Red Onion', quantityText: '2 large' },
      { name: 'Vegetable Oil', quantityText: '½ cup' },
      { name: 'Tomato Paste', quantityText: '100g' },
      { name: 'Chicken or Beef Stock', quantityText: '2 cups' },
      { name: 'Curry Powder', quantityText: '2 tbsp' },
      { name: 'Dried Thyme', quantityText: '1 tsp' },
      { name: 'Bay Leaves', quantityText: '2 leaves' },
      { name: 'Seasoning Cubes', quantityText: '2 cubes' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Blend the plum tomatoes, red bell peppers, scotch bonnet, and one onion until smooth. Pour into a pot and boil on medium-high heat for 20 minutes, stirring occasionally, until reduced by half and the water has evaporated.',
      'In a large, heavy-bottomed pot, heat the vegetable oil over medium heat. Slice the remaining onion and fry for 3–4 minutes until translucent and lightly golden. Add the tomato paste and fry for 5 minutes, stirring constantly to remove the raw, acidic taste.',
      'Add the reduced blended pepper mixture to the fried tomato paste. Stir in the curry powder, dried thyme, bay leaves, and crumbled seasoning cubes. Fry the stew on medium heat for 15–20 minutes, stirring frequently, until the oil visibly rises to the surface.',
      'Rinse the parboiled rice under cold water several times until the water runs completely clear. Drain thoroughly. This removes excess starch and prevents the rice from becoming gummy.',
      'Add the drained rice directly into the fried tomato stew. Stir well to coat every grain with the stew. Pour in the chicken or beef stock — the liquid level should be exactly level with the rice surface, not above it.',
      'Season with salt to taste. Bring the pot to a vigorous boil uncovered. Once boiling, cover the pot tightly with foil paper, then place the lid on top to create a perfect seal. Reduce heat to the absolute minimum.',
      'Cook on the lowest heat possible for 30–35 minutes. Do not open the pot. The rice will steam and cook from within. For authentic party smokiness, allow the bottom to catch slightly — this "bottom pot" is prized in West Africa.',
      'After 30 minutes, open the pot and gently fluff the rice with a fork. If any liquid remains, cover and cook for 5 more minutes. Discard bay leaves. Serve hot with fried chicken, moin moin, or coleslaw.',
    ],
  },
  {
    slug: 'egusi-soup',
    title: 'Egusi Soup',
    heroImage: '/recipes/egusi-soup.jpg',
    cookTimeMin: 50,
    servings: 6,
    category: 'Nigerian',
    difficulty: 'Medium',
    description: 'A rich, earthy soup made from ground melon seeds, bold palm oil, and leafy vegetables. One of Nigeria\'s most beloved soups, paired with pounded yam, eba, or fufu.',
    ingredients: [
      { name: 'Ground Egusi (Melon Seeds)', quantityText: '2 cups' },
      { name: 'Red Palm Oil', quantityText: '½ cup', sku: 'PALM-OIL-500' },
      { name: 'Smoked Stockfish', quantityText: '200g' },
      { name: 'Crayfish (ground)', quantityText: '3 tbsp' },
      { name: 'Scotch Bonnet Peppers', quantityText: '3 (blended)' },
      { name: 'Red Onion', quantityText: '1 medium' },
      { name: 'Ugu (Fluted Pumpkin Leaves) or Spinach', quantityText: '200g' },
      { name: 'Stockfish Bones', quantityText: '100g' },
      { name: 'Seasoning Cubes', quantityText: '2 cubes' },
      { name: 'Locust Beans (Iru/Dawadawa)', quantityText: '1 tbsp' },
      { name: 'Salt', quantityText: 'To taste' },
      { name: 'Water', quantityText: '2 cups' },
    ],
    steps: [
      'Soak the stockfish and stockfish bones in boiling water for 20–30 minutes until softened. Drain, remove bones, and break into smaller pieces. Season with a little salt and seasoning cube, then set aside.',
      'Blend the scotch bonnet peppers and half the onion to a coarse paste. Finely chop the remaining half onion. Mix the ground egusi with just enough water (3–4 tbsp) to form a thick paste — it should hold its shape.',
      'Heat the palm oil in a wide pot over medium heat until it liquifies (do not bleach). Add the chopped onion and fry for 2 minutes. Add the blended pepper paste and fry for 10 minutes, stirring, until the oil separates and rises.',
      'Drop spoonfuls of the egusi paste carefully into the hot stew — do not stir yet. Allow to fry for 5 minutes, then gently fold in. The egusi will start to clump and fry, developing a golden crust. This frying step is key to depth of flavour.',
      'Add 2 cups of water, the ground crayfish, locust beans, and crumbled seasoning cubes. Stir gently. Add the softened stockfish. Cover and cook on medium-low heat for 20 minutes, stirring occasionally.',
      'Taste and adjust seasoning with salt. Add the sliced ugu leaves (or washed spinach) and stir through. Cook for just 3–5 more minutes — the greens should remain bright and vibrant, not overcooked.',
      'Serve immediately with freshly pounded yam, eba (garri), or fufu. The soup should be thick, rich, and coat the pounded yam generously.',
    ],
  },
  {
    slug: 'suya-grilled-beef-skewers',
    title: 'Suya — West African Spiced Beef Skewers',
    heroImage: '/recipes/suya-grilled-beef-skewers.jpg',
    cookTimeMin: 40,
    servings: 4,
    category: 'Nigerian',
    difficulty: 'Easy',
    description: 'Northern Nigeria\'s most iconic street food — thinly sliced beef marinated in a bold spiced groundnut (peanut) rub, skewered and grilled over open flame. Served with raw onion, tomato, and suya spice.',
    ingredients: [
      { name: 'Beef Sirloin or Rump', quantityText: '600g, thinly sliced' },
      { name: 'Suya Spice (Yaji)', quantityText: '4 tbsp' },
      { name: 'Groundnut Powder (roasted peanuts, ground)', quantityText: '4 tbsp' },
      { name: 'Vegetable Oil', quantityText: '2 tbsp' },
      { name: 'Garlic Powder', quantityText: '1 tsp' },
      { name: 'Ginger Powder', quantityText: '1 tsp' },
      { name: 'Paprika', quantityText: '1 tsp' },
      { name: 'Salt', quantityText: '1 tsp' },
      { name: 'Red Onion', quantityText: '1 large (to serve)' },
      { name: 'Tomatoes', quantityText: '2 (to serve)' },
      { name: 'Wooden Skewers', quantityText: '12 (soaked in water)' },
    ],
    steps: [
      'Slice the beef against the grain into very thin strips, approximately 1cm thick. The thinner the slice, the better the suya will absorb the marinade and caramelise on the grill.',
      'Make the suya marinade: combine suya spice, ground peanut powder, garlic powder, ginger powder, paprika, salt, and vegetable oil in a bowl. Mix into a thick, fragrant paste.',
      'Coat each beef strip generously in the suya spice paste, pressing it firmly into the meat. Thread the coated strips onto pre-soaked wooden skewers in a flat, ribbon-like fashion. Refrigerate for at least 1 hour, or overnight for maximum flavour.',
      'Preheat your grill, barbecue, or griddle pan to high heat. Lightly oil the grates. Grill the suya skewers for 4–5 minutes per side, pressing down occasionally, until nicely charred with crispy edges but still juicy inside.',
      'While the suya is hot, dust with a final sprinkle of extra suya spice. Serve immediately on a wooden board with thinly sliced raw red onion, fresh tomato wedges, and more yaji spice on the side.',
    ],
  },
  {
    slug: 'fried-plantain-dodo',
    title: 'Fried Sweet Plantain (Dodo)',
    heroImage: '/recipes/fried-plantain-dodo.jpg',
    cookTimeMin: 15,
    servings: 4,
    category: 'Nigerian',
    difficulty: 'Easy',
    description: 'Golden, caramelised fried ripe plantain — the sweet companion to jollof rice, beans, or fried eggs. Simple but utterly addictive. The key is using deeply ripe, black-spotted plantain.',
    ingredients: [
      { name: 'Very Ripe Plantains (black-spotted)', quantityText: '3 large', sku: 'PLANTAIN-RIPE' },
      { name: 'Vegetable Oil', quantityText: '1 cup (for shallow frying)' },
      { name: 'Salt', quantityText: 'A pinch (optional)' },
    ],
    steps: [
      'Peel the plantains. The riper they are — soft with black spots all over — the sweeter and better the dodo will be. Do not use unripe or semi-ripe yellow plantain for this dish.',
      'Cut the plantain diagonally into 1.5cm thick slices. Diagonal cuts give more surface area for caramelisation. If you want, sprinkle a tiny pinch of salt over the pieces.',
      'Heat the oil in a wide, shallow frying pan over medium heat. The oil should be about 2cm deep. Test readiness by dropping a small piece in — it should sizzle immediately.',
      'Carefully add the plantain slices in a single layer. Do not overcrowd. Fry for 3–4 minutes until the bottom is deep golden-brown and caramelised. Flip and fry for another 2–3 minutes.',
      'Remove with a slotted spoon and drain on kitchen paper. Serve hot alongside jollof rice, fried eggs, beans, or as a standalone snack. Best eaten the moment it comes out of the pan.',
    ],
  },
  {
    slug: 'groundnut-peanut-soup',
    title: 'Groundnut Soup (Peanut Stew)',
    heroImage: '/recipes/groundnut-peanut-soup.jpg',
    cookTimeMin: 60,
    servings: 6,
    category: 'West African',
    difficulty: 'Medium',
    description: 'A luxuriously creamy, nutty stew made with ground roasted peanuts, tomatoes, and your choice of meat or fish. Found across West Africa from Nigeria to Ghana and Senegal, each with its own regional character.',
    ingredients: [
      { name: 'Roasted Groundnut Paste (peanut butter, smooth)', quantityText: '1 cup' },
      { name: 'Chicken Thighs or Beef', quantityText: '600g' },
      { name: 'Plum Tomatoes', quantityText: '3 medium' },
      { name: 'Red Onion', quantityText: '1 large' },
      { name: 'Scotch Bonnet Pepper', quantityText: '1–2' },
      { name: 'Garlic', quantityText: '3 cloves' },
      { name: 'Fresh Ginger', quantityText: '1 inch piece' },
      { name: 'Tomato Paste', quantityText: '2 tbsp' },
      { name: 'Vegetable Oil', quantityText: '3 tbsp' },
      { name: 'Chicken Stock', quantityText: '500ml' },
      { name: 'Seasoning Cubes', quantityText: '2 cubes' },
      { name: 'Fresh Coriander or Parsley', quantityText: 'Handful, to serve' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Season the chicken or beef generously with salt, pepper, and one crumbled seasoning cube. In a heavy pot, heat 2 tbsp oil and brown the meat in batches on all sides. Remove and set aside.',
      'In the same pot, add the remaining oil. Finely dice the onion and fry for 5 minutes until golden. Add minced garlic and grated ginger, fry for 1 minute until fragrant.',
      'Blend the tomatoes, scotch bonnet, and half the onion into a smooth sauce. Pour into the pot with the tomato paste. Fry for 10–12 minutes on medium heat until thickened and the oil separates.',
      'Add the chicken stock and browned meat back to the pot. Bring to a simmer. Stir in the groundnut paste gradually, mixing until completely smooth and incorporated. The soup will thicken considerably.',
      'Cover and simmer on low heat for 25–30 minutes, stirring every 10 minutes to prevent the bottom from catching. The oil will rise to the surface. Season with salt and seasoning cube to taste.',
      'Serve over plain white rice, with boiled yam, or with crusty bread. Garnish with fresh coriander or parsley. Add a squeeze of lime for brightness.',
    ],
  },
  {
    slug: 'efo-riro-nigerian-spinach-stew',
    title: 'Efo Riro — Nigerian Spinach Stew',
    heroImage: '/recipes/efo-riro-nigerian-spinach-stew.jpg',
    cookTimeMin: 45,
    servings: 5,
    category: 'Nigerian',
    difficulty: 'Medium',
    description: 'A vibrant, deeply flavoured Yoruba stew of wilted spinach or ugu leaves, cooked with palm oil, assorted meats, and crayfish. More than a soup — it\'s the taste of Sunday in Southwest Nigeria.',
    ingredients: [
      { name: 'Fresh Spinach or Ugu Leaves', quantityText: '500g, washed' },
      { name: 'Red Palm Oil', quantityText: '⅓ cup', sku: 'PALM-OIL-500' },
      { name: 'Assorted Meat (tripe, cow foot, beef)', quantityText: '400g, pre-cooked' },
      { name: 'Smoked Fish', quantityText: '150g' },
      { name: 'Crayfish (ground)', quantityText: '2 tbsp' },
      { name: 'Scotch Bonnet Peppers', quantityText: '3' },
      { name: 'Red Bell Pepper', quantityText: '1 large' },
      { name: 'Red Onion', quantityText: '1 medium' },
      { name: 'Locust Beans (Iru)', quantityText: '1 tbsp' },
      { name: 'Seasoning Cubes', quantityText: '2 cubes' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Wash the spinach or ugu thoroughly. Roughly chop into large pieces — not too finely, as the leaves will wilt significantly. Set aside. Debone the smoked fish and break into chunks.',
      'Blend the scotch bonnet peppers, red bell pepper, and onion to a medium-coarse paste — not completely smooth. You want some texture.',
      'Heat the palm oil in a pot over medium heat until it liquifies and shimmers. Add the blended pepper mix and fry vigorously for 10–15 minutes, stirring frequently, until darkened and the oil rises to the surface.',
      'Add the crayfish, locust beans, and crumbled seasoning cubes. Stir well. Add the pre-cooked assorted meat and the smoked fish. Cook for 5 minutes, mixing everything together.',
      'Add the spinach or ugu leaves and fold through the stew. Do not add any water — the leaves will release their own moisture. Cook on high heat for 3–4 minutes, uncovered, until wilted but still bright green. Over-cooking ruins the colour.',
      'Taste and adjust seasoning. The stew should be thick, aromatic, and vibrant green-red. Serve with pounded yam, eba, or rice.',
    ],
  },
  {
    slug: 'ogbono-soup',
    title: 'Ogbono Soup (Wild Mango Seed Soup)',
    heroImage: '/recipes/ogbono-soup.jpg',
    cookTimeMin: 50,
    servings: 6,
    category: 'Nigerian',
    difficulty: 'Medium',
    description: 'A thick, viscous, draw soup made from ground ogbono (wild African mango seeds). Its distinctive slippery texture makes it perfect for swallowing with pounded yam or eba. Deep, nutty, and unmistakably West African.',
    ingredients: [
      { name: 'Ground Ogbono Seeds', quantityText: '1 cup' },
      { name: 'Red Palm Oil', quantityText: '⅓ cup', sku: 'PALM-OIL-500' },
      { name: 'Beef or Assorted Meat', quantityText: '400g, pre-cooked' },
      { name: 'Stockfish', quantityText: '100g, soaked and softened' },
      { name: 'Crayfish (ground)', quantityText: '2 tbsp' },
      { name: 'Scotch Bonnet Peppers', quantityText: '2 (blended)' },
      { name: 'Okra (optional, for extra viscosity)', quantityText: '5 fingers' },
      { name: 'Spinach or Ugu Leaves', quantityText: '100g' },
      { name: 'Locust Beans', quantityText: '1 tbsp' },
      { name: 'Seasoning Cubes', quantityText: '2 cubes' },
      { name: 'Water', quantityText: '2–3 cups' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Soak the stockfish in hot water for 30 minutes. Drain and debone. Mix the ground ogbono with the palm oil until it forms a smooth, dark paste — no dry lumps remaining.',
      'Heat a clean pot and add the ogbono-palm oil paste directly. Fry on medium heat, stirring constantly for 5 minutes until fragrant and darker in colour. The frying step activates the draw texture.',
      'Add 2 cups of warm water and stir vigorously. The ogbono will immediately begin to thicken and pull. Add the pre-cooked meat, stockfish, and blended scotch bonnet peppers.',
      'Add the ground crayfish, locust beans, and crumbled seasoning cubes. Stir well. Cover and simmer on low heat for 20 minutes. If the soup becomes too thick, add a little warm water.',
      'If using okra, chop finely and stir in now. Add the spinach or ugu and fold through. Cook uncovered for 3 minutes. Season with salt. The soup should be thick and viscous — it should "draw" when lifted with a spoon.',
      'Serve immediately with pounded yam, eba, or fufu. The "draw" texture is the hallmark of great ogbono soup.',
    ],
  },
  {
    slug: 'moin-moin-steamed-bean-pudding',
    title: 'Moin Moin — Steamed Bean Pudding',
    heroImage: '/recipes/moin-moin-steamed-bean-pudding.jpg',
    cookTimeMin: 60,
    servings: 8,
    category: 'Nigerian',
    difficulty: 'Medium',
    description: 'A beloved Nigerian steamed savoury cake made from blended black-eyed peas, peppers, and palm oil. Stuffed with egg, fish, or corned beef. Eaten as a side dish, snack, or full meal.',
    ingredients: [
      { name: 'Dried Black-Eyed Beans', quantityText: '2 cups' },
      { name: 'Red Bell Pepper (Tatashe)', quantityText: '2 large' },
      { name: 'Scotch Bonnet Pepper', quantityText: '1' },
      { name: 'Red Onion', quantityText: '1 medium' },
      { name: 'Red Palm Oil', quantityText: '¼ cup', sku: 'PALM-OIL-500' },
      { name: 'Hard-Boiled Eggs', quantityText: '4 (halved)' },
      { name: 'Canned Sardines or Corned Beef', quantityText: '1 can' },
      { name: 'Crayfish (ground)', quantityText: '1 tbsp' },
      { name: 'Vegetable Stock or Water', quantityText: '1 cup' },
      { name: 'Seasoning Cubes', quantityText: '2 cubes' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Soak the dried beans in cold water for 4–6 hours, or in hot water for 1 hour. Drain and peel the skin by rubbing the beans between your palms and rinsing away the skins. Repeat until the beans are clean and white.',
      'Blend the peeled beans with the red bell pepper, scotch bonnet, onion, and just enough water (about ½ cup) to create a very smooth, lump-free paste. The blending is key — blend for at least 3 minutes until silky smooth.',
      'Transfer the paste to a large bowl. Add the palm oil, ground crayfish, crumbled seasoning cubes, and salt. Stir vigorously in one direction for 3–4 minutes to incorporate air — this gives a lighter texture.',
      'Gradually add stock or warm water until the batter flows slowly off a spoon like thick pancake batter. Do not make it too loose. Taste and adjust seasoning.',
      'Grease your moulds (foil cups, ramekins, or moin moin leaves). Spoon batter into each mould, filling halfway. Add a piece of egg and sardine to each. Cover with more batter to the top. Seal tightly.',
      'Place in a pot of boiling water (water should reach halfway up the moulds). Cover the pot tightly. Steam for 45–50 minutes on medium heat, adding more water as needed. The moin moin is ready when firm to the touch and pulls away from the sides.',
      'Allow to cool for 5 minutes before unmoulding. Serve warm alongside jollof rice, ogi (corn porridge), or on its own as a protein-rich snack.',
    ],
  },
  {
    slug: 'akara-bean-fritters',
    title: 'Akara — Crispy Bean Fritters',
    heroImage: '/recipes/akara-bean-fritters.jpg',
    cookTimeMin: 35,
    servings: 4,
    category: 'Nigerian',
    difficulty: 'Easy',
    description: 'Light, crispy, and deeply savoury fritters made from blended black-eyed peas. A staple breakfast or street food across West Africa, served with ogi (pap) or eaten as a snack. The aeration technique is the secret to their fluffiness.',
    ingredients: [
      { name: 'Dried Black-Eyed Beans', quantityText: '1 cup' },
      { name: 'Red Onion', quantityText: '½ medium' },
      { name: 'Scotch Bonnet Pepper', quantityText: '1' },
      { name: 'Crayfish (ground)', quantityText: '1 tbsp' },
      { name: 'Seasoning Cube', quantityText: '1 cube' },
      { name: 'Vegetable Oil', quantityText: '2 cups (for deep frying)' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Soak the beans in cold water for 2 hours. Drain and rub vigorously between your palms to remove the skins. Rinse in cold water multiple times until all the dark skins have floated away and the beans are clean and ivory-white.',
      'Blend the peeled beans with the onion, scotch bonnet, and just enough water (2–3 tbsp) to produce a thick, smooth, creamy paste. The less water used, the crispier the akara. Blend for at least 2–3 minutes until completely smooth.',
      'Transfer the paste to a bowl. Add ground crayfish, crumbled seasoning cube, and salt. Now beat the mixture vigorously with a wooden spoon or electric mixer for 3–4 minutes. This step incorporates air, making the fritters light and puffed.',
      'Heat the vegetable oil in a deep pot to 175°C / 350°F. Test by dropping a small amount of batter in — it should rise to the surface immediately and sizzle vigorously.',
      'Using a wet tablespoon, carefully drop spoonfuls of batter into the hot oil. Do not overcrowd. Fry for 3–4 minutes until the bottom is golden brown, then turn and fry the other side for 2–3 more minutes.',
      'Remove with a slotted spoon and drain on kitchen paper. Serve immediately while hot and crispy alongside ogi (pap), akamu, or enjoy as a standalone snack with chilli sauce.',
    ],
  },
  {
    slug: 'banga-soup-palm-fruit',
    title: 'Banga Soup — Delta Palm Fruit Soup',
    heroImage: '/recipes/banga-soup-palm-fruit.jpg',
    cookTimeMin: 90,
    servings: 6,
    category: 'Nigerian',
    difficulty: 'Advanced',
    description: 'A distinctive, aromatic soup from the Niger Delta — made by extracting thick cream from freshly cooked palm fruits, seasoned with oburunbebe stick, stew banga spice mix, and periwinkles. Served with starch or white rice.',
    ingredients: [
      { name: 'Fresh or Canned Palm Fruits', quantityText: '800g' },
      { name: 'Beef or Catfish', quantityText: '500g' },
      { name: 'Periwinkles (cleaned)', quantityText: '200g' },
      { name: 'Banga Spice Mix', quantityText: '2 tbsp' },
      { name: 'Dried Oburunbebe Stick', quantityText: '1 small stick' },
      { name: 'Crayfish (ground)', quantityText: '2 tbsp' },
      { name: 'Scotch Bonnet Pepper', quantityText: '2' },
      { name: 'Red Onion', quantityText: '1 medium' },
      { name: 'Fresh Tomatoes', quantityText: '2' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Fresh Beletete Leaves or Efinrin (basil)', quantityText: 'Small handful' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'If using fresh palm fruits, cook in a large pot of water for 30 minutes until very soft. Drain, allow to cool slightly, then pound in a mortar to break up the flesh. Add warm water and knead to extract the thick orange cream. Strain through a sieve, discarding the fibres and seeds.',
      'If using canned palm fruit cream, tip directly into a pot and add enough water to make approximately 1 litre of working liquid.',
      'Bring the palm cream to a boil. Add the washed and seasoned meat or fish. Add the oburunbebe stick, blended scotch bonnet and onion, and ground crayfish.',
      'Simmer on medium heat for 20 minutes. Add the banga spice mix, crumbled seasoning cubes, and periwinkles. Stir well.',
      'Continue cooking on medium-low heat for 20–25 minutes until the soup thickens and the oil rises to the surface. Remove the oburunbebe stick.',
      'Stir in the fresh beletete leaves or efinrin. Cook for 5 more minutes. Season with salt. The soup should be thick, deeply orange, and aromatic. Serve with cassava starch (starch) or white rice.',
    ],
  },
  {
    slug: 'kelewele-ghanaian-spiced-plantain',
    title: 'Kelewele — Ghanaian Spiced Fried Plantain',
    heroImage: 'https://images.unsplash.com/photo-1536304993881-ff86e0c9e8a6?w=1200&h=800&fit=crop&q=85',
    cookTimeMin: 25,
    servings: 4,
    category: 'Ghanaian',
    difficulty: 'Easy',
    description: 'Ghana\'s answer to flavoured fried plantain — ripe plantain cubes marinated in ginger, cloves, cayenne, and spices, then fried until deeply caramelised. A popular street food and party side dish.',
    ingredients: [
      { name: 'Very Ripe Plantains', quantityText: '3 large', sku: 'PLANTAIN-RIPE' },
      { name: 'Fresh Ginger', quantityText: '1 inch, grated' },
      { name: 'Cayenne Pepper or Chilli Powder', quantityText: '1 tsp' },
      { name: 'Ground Cloves', quantityText: '¼ tsp' },
      { name: 'Ground Nutmeg', quantityText: '¼ tsp' },
      { name: 'Anise Seeds or Ground Anise', quantityText: '¼ tsp' },
      { name: 'Salt', quantityText: '½ tsp' },
      { name: 'Vegetable Oil', quantityText: '1 cup (for deep frying)' },
    ],
    steps: [
      'Peel the ripe plantains and cut into rough 2cm cubes. The plantain should be very ripe — deeply yellow with black spots — for maximum sweetness and caramelisation.',
      'Mix the grated ginger, cayenne, ground cloves, nutmeg, anise, and salt in a bowl. Add the plantain cubes and toss well to coat every piece. The spices should cling to the surface. Leave to marinate for 15–20 minutes.',
      'Heat the oil in a heavy pan to 170°C / 340°F. The plantains release sugar as they cook, so a slightly lower temperature prevents burning while ensuring deep caramelisation.',
      'Fry the marinated plantain cubes in batches for 5–6 minutes, turning occasionally, until deeply golden-brown and caramelised on all sides. The ginger and spices will create an incredible fragrant crust.',
      'Drain on kitchen paper and serve hot. Kelewele is traditionally served with roasted groundnuts. Perfect alongside waakye, grilled fish, or as a standalone snack.',
    ],
  },
  {
    slug: 'waakye-rice-and-beans',
    title: 'Waakye — Ghanaian Rice and Beans',
    heroImage: '/recipes/waakye-rice-and-beans.jpg',
    cookTimeMin: 90,
    servings: 6,
    category: 'Ghanaian',
    difficulty: 'Medium',
    description: 'Ghana\'s iconic street food of rice and black-eyed peas (or sorghum beans) cooked together with millet stalks for a distinctive reddish-brown colour. Served with stew, fried fish, kelewele, spaghetti, and a range of accompaniments.',
    ingredients: [
      { name: 'Long Grain Rice', quantityText: '2 cups' },
      { name: 'Black-Eyed Peas or Red Kidney Beans', quantityText: '1 cup' },
      { name: 'Dried Sorghum Leaves or Waakye Leaves', quantityText: '3 pieces (for colour)' },
      { name: 'Water', quantityText: '4 cups' },
      { name: 'Salt', quantityText: '1½ tsp' },
      { name: 'Vegetable Oil', quantityText: '1 tbsp' },
      { name: 'For the Stew: Canned Tomatoes', quantityText: '1 can' },
      { name: 'For the Stew: Red Onion', quantityText: '1 large' },
      { name: 'For the Stew: Vegetable Oil', quantityText: '¼ cup' },
      { name: 'For the Stew: Scotch Bonnet', quantityText: '1–2' },
      { name: 'For the Stew: Chicken Stock Cubes', quantityText: '2' },
      { name: 'Fried Fish or Chicken', quantityText: 'To serve' },
    ],
    steps: [
      'Soak the black-eyed peas overnight, or use the quick method: cover with boiling water and soak for 1 hour. Drain and rinse. Parboil the beans in fresh water for 20 minutes until just starting to soften but not fully cooked.',
      'Bring 4 cups of fresh water to a boil. Add the dried sorghum leaves and boil for 5 minutes. The water will turn a dark reddish-brown — this is the natural dye that colours the waakye. Remove the leaves.',
      'Add the parboiled beans to the coloured water. Cook for 10 minutes on medium-high. Add the rice, oil, and salt. Stir once, then cover tightly.',
      'Reduce heat to low and cook for 25–30 minutes until all the water is absorbed and both the rice and beans are tender. The waakye should have a light reddish-brown hue throughout.',
      'Meanwhile, make the tomato stew: blend tomatoes, onion, and scotch bonnet. Fry in oil for 15–20 minutes. Season with stock cubes and salt.',
      'Serve the waakye topped with the tomato stew, fried fish or chicken, sliced boiled eggs, spaghetti, kelewele, shito (pepper sauce), and gari. The more accompaniments, the more authentic the experience.',
    ],
  },
  {
    slug: 'pepper-soup',
    title: 'Nigerian Pepper Soup',
    heroImage: '/recipes/pepper-soup.jpg',
    cookTimeMin: 45,
    servings: 4,
    category: 'Nigerian',
    difficulty: 'Easy',
    description: 'A boldly spiced, aromatic, and deeply warming clear broth made with a unique blend of West African spices. Traditionally served as a medicinal soup for illness and cold weather, and as a celebratory dish at births. Made with goat meat, catfish, or chicken.',
    ingredients: [
      { name: 'Goat Meat or Catfish or Chicken', quantityText: '600g' },
      { name: 'Pepper Soup Spice Mix', quantityText: '3 tbsp' },
      { name: 'Scotch Bonnet Peppers', quantityText: '2–3' },
      { name: 'Red Onion', quantityText: '1 large' },
      { name: 'Fresh Uziza Leaves (or African Basil)', quantityText: 'Small handful' },
      { name: 'Crayfish (ground)', quantityText: '1 tbsp' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Water', quantityText: '1.5 litres' },
      { name: 'Salt', quantityText: 'To taste' },
      { name: 'Utazi Leaves (optional, for bitterness)', quantityText: 'A few leaves' },
    ],
    steps: [
      'Wash the goat meat or fish thoroughly. If using goat meat, cut into large chunks and season with 1 tbsp pepper soup spice, half the onion (roughly chopped), and a pinch of salt. Allow to marinate for 30 minutes.',
      'Place the seasoned meat in a pot with 500ml water. Cook on high heat for 20–25 minutes (goat meat needs pre-cooking). For fish, skip this step.',
      'Add the remaining water to the pot. Bring to a boil. Add the remaining pepper soup spice mix, blended scotch bonnet, the rest of the onion, and ground crayfish.',
      'Add the crumbled seasoning cubes and stir well. If using fresh fish, add now. Reduce heat to a vigorous simmer and cook for 15 minutes.',
      'Taste and adjust heat and seasoning. The broth should be clear, deeply aromatic, and quite spicy. Add salt to taste.',
      'Tear the uziza leaves (if using) and add for the last 2 minutes. Serve in deep bowls as a starter, with agidi (corn cake), white rice, or simply as a warming soup. Popular with cold Guinness alongside.',
    ],
  },
  {
    slug: 'ofada-rice-ayamase',
    title: 'Ofada Rice with Ayamase (Designer Stew)',
    heroImage: '/recipes/ofada-rice-ayamase.jpg',
    cookTimeMin: 75,
    servings: 4,
    category: 'Nigerian',
    difficulty: 'Advanced',
    description: 'The unrefined, fragrant local Nigerian Ofada rice paired with the famously potent Ayamase — a green, unripe pepper stew made with bleached palm oil and assorted offal. A heritage dish with a fierce, acquired flavour.',
    ingredients: [
      { name: 'Ofada Rice (local Nigerian unrefined rice)', quantityText: '2 cups' },
      { name: 'Red Palm Oil (for bleaching)', quantityText: '1 cup' },
      { name: 'Green Scotch Bonnet Peppers (unripe)', quantityText: '8–10' },
      { name: 'Green Bell Peppers', quantityText: '3' },
      { name: 'Assorted Offal (tripe, cow skin, kidney)', quantityText: '500g, pre-cooked' },
      { name: 'Locust Beans (Iru)', quantityText: '2 tbsp' },
      { name: 'Hard-Boiled Eggs', quantityText: '4' },
      { name: 'Crayfish (ground)', quantityText: '2 tbsp' },
      { name: 'Red Onion', quantityText: '1' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Wash the ofada rice in several changes of water to remove excess bran. Soak in cold water for 30 minutes, then drain. Cook in salted water for 25–30 minutes until tender but still with a slight bite. Drain.',
      'Blend the green scotch bonnet peppers, green bell peppers, and onion to a coarse paste — not completely smooth. The green colour is signature to Ayamase.',
      'Bleach the palm oil: heat in a wide pan over high heat for 15–20 minutes until it turns from orange to a clear yellow and the smoke begins. This is the "bleaching" step unique to Ayamase. Do not leave unattended. Allow to cool slightly.',
      'Return the bleached oil to medium heat. Add the blended green pepper paste and fry hard for 20–25 minutes, stirring frequently, until all the moisture has dried out completely and the paste is dark and very fragrant.',
      'Add the locust beans, ground crayfish, seasoning cubes, and pre-cooked assorted offal. Stir well and cook for 10 minutes. Add the whole boiled eggs and coat in the stew.',
      'Season with salt. Serve the Ofada rice in banana leaves (for authenticity) or on plates, topped generously with the Ayamase stew. The combination of the earthy rice and ferocious green stew is extraordinary.',
    ],
  },
  {
    slug: 'puff-puff',
    title: 'Puff Puff — Nigerian Fried Dough Balls',
    heroImage: '/recipes/puff-puff.jpg',
    cookTimeMin: 40,
    servings: 6,
    category: 'Nigerian',
    difficulty: 'Easy',
    description: 'The most beloved West African street snack — golden, pillowy deep-fried dough balls with a slight sweetness and fluffy interior. Essential at parties, markets, and roadside stalls from Lagos to Accra.',
    ingredients: [
      { name: 'Plain Flour', quantityText: '2 cups' },
      { name: 'Instant Yeast', quantityText: '2 tsp' },
      { name: 'Granulated Sugar', quantityText: '3 tbsp' },
      { name: 'Salt', quantityText: '½ tsp' },
      { name: 'Ground Nutmeg', quantityText: '¼ tsp' },
      { name: 'Warm Water', quantityText: '¾ cup' },
      { name: 'Vegetable Oil', quantityText: '2 cups (for deep frying)' },
    ],
    steps: [
      'Mix the flour, yeast, sugar, salt, and ground nutmeg in a large bowl. Gradually add the warm water, mixing continuously until a smooth, thick batter forms. It should be pourable but not runny — consistency of thick pancake batter.',
      'Cover the bowl with cling film or a damp cloth and leave in a warm place for 1 hour until the batter has puffed up noticeably and tiny bubbles appear on the surface. The yeast is doing its work.',
      'Heat the vegetable oil in a deep pot to 175°C / 350°F. You want enough oil depth so the puff puff can float and turn. Test the temperature by dropping a tiny bit of batter — it should rise immediately and sizzle.',
      'Using wet hands or a spoon, scoop portions of batter and gently drop into the hot oil. Aim for round shapes. Do not overcrowd — they need room to puff and turn.',
      'Fry for 3–4 minutes, turning occasionally, until evenly golden brown all over. The puff puff should be hollow inside with a thin, crispy exterior.',
      'Remove with a slotted spoon and drain on kitchen paper. Serve hot — either plain or dusted with icing sugar. Optional: dip in a chilli sauce for a sweet-hot contrast.',
    ],
  },
  {
    slug: 'nigerian-fried-rice',
    title: 'Nigerian Party Fried Rice',
    heroImage: '/recipes/nigerian-fried-rice.jpg',
    cookTimeMin: 55,
    servings: 8,
    category: 'Nigerian',
    difficulty: 'Medium',
    description: 'Unlike Chinese-style fried rice, Nigerian fried rice is cooked in chicken stock with liver, green beans, sweetcorn, peas, and carrots. Rich, golden, and perfectly seasoned — a fixture at every Nigerian celebration alongside jollof rice.',
    ingredients: [
      { name: 'Long Grain Rice', quantityText: '3 cups, parboiled' },
      { name: 'Chicken Liver', quantityText: '200g, diced' },
      { name: 'Chicken Stock', quantityText: '600ml' },
      { name: 'Mixed Vegetables (peas, carrots, sweetcorn, green beans)', quantityText: '300g' },
      { name: 'Spring Onions', quantityText: '1 bunch' },
      { name: 'Vegetable Oil', quantityText: '4 tbsp' },
      { name: 'Curry Powder', quantityText: '3 tsp' },
      { name: 'Thyme', quantityText: '1 tsp' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Soy Sauce', quantityText: '2 tbsp' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Parboil the rice in lightly salted water for 10 minutes — it should be about 60% cooked. Drain and set aside. This two-stage cooking method ensures each grain stays separate.',
      'Heat 2 tbsp oil in a large wok or wide pan over high heat. Season the diced chicken liver with salt and curry powder. Fry for 5–7 minutes until cooked through and slightly caramelised. Remove and set aside.',
      'In the same pan over high heat, add the remaining oil. Add the mixed vegetables and spring onions. Stir-fry for 3 minutes until slightly tender but still vibrant. The high heat creates the characteristic slightly charred flavour.',
      'Add the parboiled rice to the vegetables. Pour in the warm chicken stock. Add curry powder, thyme, crumbled seasoning cubes, and soy sauce. Stir everything together thoroughly.',
      'Cover and cook on medium heat for 15–20 minutes until the stock is fully absorbed and the rice is cooked through and golden. Stir halfway through to ensure even cooking.',
      'Add the cooked liver back in and fold through gently. Taste and adjust seasoning. The rice should be yellow-golden, with visible vegetables and liver distributed throughout. Serve with fried chicken, coleslaw, and moin moin.',
    ],
  },
  {
    slug: 'abacha-african-salad',
    title: 'Abacha — Igbo African Salad',
    heroImage: '/recipes/abacha-african-salad.jpg',
    cookTimeMin: 30,
    servings: 4,
    category: 'Nigerian',
    difficulty: 'Medium',
    description: 'An ancient Igbo delicacy made from dried, shredded cassava rehydrated and dressed with palm oil, ugba (fermented oil bean seeds), garden eggs, crayfish, and leafy herbs. A textural, complex dish of umami and earthiness.',
    ingredients: [
      { name: 'Dried Abacha (shredded cassava)', quantityText: '2 cups' },
      { name: 'Ugba (Ukpaka / Fermented Oil Bean Seeds)', quantityText: '100g' },
      { name: 'Red Palm Oil', quantityText: '5 tbsp', sku: 'PALM-OIL-500' },
      { name: 'Potash (Akanwu/Kaun)', quantityText: '1 tsp' },
      { name: 'Crayfish (ground)', quantityText: '2 tbsp' },
      { name: 'Scotch Bonnet Pepper', quantityText: '1 (ground)' },
      { name: 'Stockfish (softened)', quantityText: '100g' },
      { name: 'Canned Mackerel or Smoked Fish', quantityText: '200g' },
      { name: 'African Salad Garden Eggs', quantityText: '3 (sliced)' },
      { name: 'Fresh Utazi Leaves', quantityText: 'Handful, shredded' },
      { name: 'Red Onion', quantityText: '1 small, sliced' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Soak the dried abacha (shredded cassava) in cold water for 20 minutes until softened. Drain thoroughly and squeeze out excess water. The strands should be pliable but not mushy.',
      'Dissolve the potash in 1 tbsp warm water. Strain through a fine sieve to remove grit. Set aside — this is the emulsifier that thickens and sets the palm oil.',
      'Pour the palm oil into a clean bowl. Add the dissolved potash water drop by drop, stirring constantly. The oil will emulsify and turn a lighter, creamy orange colour. This is the key technique of abacha.',
      'Add the ground crayfish, blended scotch bonnet, and crumbled seasoning to the emulsified palm oil. Mix well. Taste — it should be bold, spicy, and deeply savoury.',
      'Add the drained abacha to the dressed palm oil. Fold in the ugba, softened stockfish pieces, and sliced garden eggs. Mix gently but thoroughly so every strand is coated.',
      'Transfer to a serving plate. Top with shredded utazi leaves, sliced red onion, and flaked smoked fish or mackerel. Serve at room temperature. Abacha is best eaten slightly warm, not cold.',
    ],
  },
  {
    slug: 'ofe-onugbu-bitter-leaf-soup',
    title: 'Ofe Onugbu — Bitter Leaf Soup',
    heroImage: '/recipes/ofe-onugbu-bitter-leaf-soup.jpg',
    cookTimeMin: 65,
    servings: 6,
    category: 'Nigerian',
    difficulty: 'Advanced',
    description: 'A classic Igbo soup made with bitter leaf (onugbu), cocoyam as a thickener, palm oil, assorted meats, stockfish, and crayfish. The bitterness of the leaves balances beautifully against the rich, starchy broth. Paired with pounded yam.',
    ingredients: [
      { name: 'Bitter Leaf (fresh, well-washed to reduce bitterness)', quantityText: '300g' },
      { name: 'Cocoyam (Ede Ede) or Cocoyam Paste', quantityText: '500g' },
      { name: 'Red Palm Oil', quantityText: '½ cup', sku: 'PALM-OIL-500' },
      { name: 'Beef, Cow Tripe, and Stockfish', quantityText: '500g combined' },
      { name: 'Ground Crayfish', quantityText: '3 tbsp' },
      { name: 'Ogiri (fermented locust bean paste)', quantityText: '1 tbsp' },
      { name: 'Scotch Bonnet', quantityText: '2 (ground)' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Salt', quantityText: 'To taste' },
      { name: 'Water', quantityText: '1.5 litres' },
    ],
    steps: [
      'Wash the fresh bitter leaf thoroughly, rubbing firmly between your palms and rinsing repeatedly — at least 5–6 times — until the water runs green but the intense bitterness is significantly reduced. Squeeze dry.',
      'Boil the cocoyams until very soft (about 25 minutes). Peel and pound in a mortar until completely smooth, or blend with a little water. The pounded cocoyam acts as the soup thickener.',
      'Season the beef and tripe with salt and seasoning cube. Cook for 20 minutes. Add the softened stockfish. Continue cooking with 1.5 litres of water until the meat is fully tender.',
      'Add the palm oil directly to the boiling stock. Add the blended scotch bonnet, ground crayfish, and ogiri. Stir and cook for 10 minutes.',
      'Add the pounded cocoyam in small pieces to the soup. Stir continuously as you add — the soup will thicken dramatically. You may need to add more water if it becomes too thick.',
      'Add the washed bitter leaf and stir through. Simmer for 10–15 minutes. Taste and adjust with salt. The soup should be thick, rich, and balanced — the bitterness of the leaf cutting through the richness of the palm oil.',
      'Serve immediately with pounded yam. This soup is traditionally made for important occasions and as a healing food.',
    ],
  },
  {
    slug: 'jollof-spaghetti',
    title: 'Jollof Spaghetti',
    heroImage: '/recipes/jollof-spaghetti.jpg',
    cookTimeMin: 35,
    servings: 4,
    category: 'West African',
    difficulty: 'Easy',
    description: 'Nigeria\'s beloved pasta dish — spaghetti cooked directly in a rich tomato-pepper stew with chicken or prawns. Spicier, bolder, and more fragrant than Italian pasta. A fusion that\'s become a staple at Nigerian parties.',
    ingredients: [
      { name: 'Spaghetti', quantityText: '400g' },
      { name: 'Canned Plum Tomatoes', quantityText: '400g' },
      { name: 'Red Bell Pepper', quantityText: '2' },
      { name: 'Scotch Bonnet Pepper', quantityText: '1' },
      { name: 'Red Onion', quantityText: '1 large' },
      { name: 'Chicken Thighs or Prawns', quantityText: '400g' },
      { name: 'Tomato Paste', quantityText: '2 tbsp' },
      { name: 'Vegetable Oil', quantityText: '4 tbsp' },
      { name: 'Curry Powder', quantityText: '1 tsp' },
      { name: 'Thyme', quantityText: '½ tsp' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Spring Onions and Coriander', quantityText: 'To garnish' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Blend the canned tomatoes, red bell peppers, scotch bonnet, and half the onion until smooth. Finely dice the remaining onion.',
      'Season the chicken with curry powder, thyme, salt, and seasoning cube. In a wide, deep pan, heat 3 tbsp oil and brown the chicken on all sides for 8–10 minutes. Remove and set aside.',
      'In the same pan, fry the diced onion for 3 minutes. Add the tomato paste and fry for 3 minutes. Pour in the blended pepper sauce and fry for 15 minutes until the oil rises and the stew is thick and fragrant.',
      'Return the browned chicken to the pan. Add 600ml water, curry powder, thyme, and crumbled seasoning cubes. Bring to a boil.',
      'Break the spaghetti in half and push directly into the tomato stock. Stir well to submerge all the pasta. Cook on medium heat for 12–15 minutes, stirring frequently, until the pasta absorbs the sauce and is fully cooked through.',
      'If the pasta looks dry before cooking through, add a splash of warm water. Taste and adjust seasoning. Garnish with sliced spring onions and fresh coriander. Serve immediately.',
    ],
  },
  {
    slug: 'okra-soup',
    title: 'Okra Soup (Draw Soup)',
    heroImage: '/recipes/okra-soup.jpg',
    cookTimeMin: 40,
    servings: 5,
    category: 'West African',
    difficulty: 'Easy',
    description: 'A quick, nutritious, and delightfully viscous soup made from finely cut okra simmered with crayfish, smoked fish, palm oil, and seasonings. The "draw" texture is beloved across West Africa and makes it ideal with swallows.',
    ingredients: [
      { name: 'Fresh Okra', quantityText: '300g' },
      { name: 'Red Palm Oil', quantityText: '¼ cup', sku: 'PALM-OIL-500' },
      { name: 'Beef or Goat Meat', quantityText: '300g, pre-cooked' },
      { name: 'Smoked Fish', quantityText: '150g' },
      { name: 'Crayfish (ground)', quantityText: '2 tbsp' },
      { name: 'Scotch Bonnet Pepper', quantityText: '2 (ground)' },
      { name: 'Red Onion', quantityText: '1 small' },
      { name: 'Locust Beans', quantityText: '1 tbsp' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Wash the okra thoroughly. For maximum draw (viscosity), grate the okra on a box grater or use a food processor to pulse briefly. Alternatively, slice very finely with a sharp knife. The finer the cut, the more draw you get.',
      'Heat the palm oil in a pot. Add the chopped onion and fry for 2 minutes. Add the blended scotch bonnet and fry for 5 minutes until the oil separates.',
      'Add the pre-cooked meat, crumbled seasoning cubes, ground crayfish, locust beans, and deboned smoked fish. Stir and cook for 5 minutes.',
      'Add 1 cup of water and bring to a simmer. Add the grated or sliced okra all at once. Stir gently — do not over-stir as this can break down the viscosity too quickly.',
      'Cook for 5–8 minutes. The okra will thicken the soup considerably and create that distinctive slippery texture. Season with salt. Do not cook the okra for too long or it loses its vibrant green colour.',
      'Serve with pounded yam, eba, or amala. The okra soup should be glossy, green-tinged, and thick enough to coat a swallow of pounded yam.',
    ],
  },
  {
    slug: 'ila-alasepo',
    title: 'Ila-Alasepo (Mixed Okra Soup)',
    heroImage: '/recipes/ila-alasepo.jpg',
    cookTimeMin: 45,
    servings: 6,
    category: 'Nigerian',
    difficulty: 'Medium',
    description: 'A luxurious, one-pot Nigerian Okra soup rich with assorted meats, seafood, and a touch of palm oil. Unlike plain okra soup, Alasepo cooks the okra directly in a highly seasoned stock.',
    ingredients: [
      { name: 'Fresh Okra', quantityText: '400g' },
      { name: 'Red Palm Oil', quantityText: '3 tbsp', sku: 'PALM-OIL-500' },
      { name: 'Assorted Meat (Beef, Cow Skin)', quantityText: '500g' },
      { name: 'Smoked Fish or Dry Fish', quantityText: '200g' },
      { name: 'Fresh Prawns', quantityText: '200g' },
      { name: 'Crayfish (ground)', quantityText: '3 tbsp' },
      { name: 'Scotch Bonnet Pepper', quantityText: '3 (blended)' },
      { name: 'Locust Beans (Iru)', quantityText: '1 tbsp' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Wash the meat thoroughly and season with salt, seasoning cube, and chopped onions. Cook until tender. Add the smoked fish in the last 10 minutes of cooking the meat.',
      'Finely chop or grate the okra to maximize the draw (viscosity). Set aside.',
      'To the boiling meat stock, add the palm oil, blended scotch bonnet peppers, crayfish, and locust beans. Allow it to boil uncovered for 10 minutes.',
      'Add the fresh prawns and cook for another 5 minutes.',
      'Stir in the chopped okra. Cook uncovered for 3-5 minutes on medium heat to retain the crunch and bright green color.',
      'Serve hot with Pounded Yam, Amala, or Eba.',
    ],
  },
  {
    slug: 'yam-porridge-asaro',
    title: 'Yam Porridge (Asaro)',
    heroImage: '/recipes/yam-porridge-asaro.jpg',
    cookTimeMin: 40,
    servings: 4,
    category: 'Nigerian',
    difficulty: 'Easy',
    description: 'A hearty and comforting one-pot dish of African yam cooked in a rich, savory tomato-pepper sauce with palm oil until it forms a thick, delicious porridge.',
    ingredients: [
      { name: 'African Yam (Puna Yam)', quantityText: '1 medium tuber' },
      { name: 'Red Palm Oil', quantityText: '1/3 cup', sku: 'PALM-OIL-500' },
      { name: 'Plum Tomatoes', quantityText: '2 medium' },
      { name: 'Red Bell Pepper (Tatashe)', quantityText: '1 large' },
      { name: 'Scotch Bonnet Pepper', quantityText: '1' },
      { name: 'Red Onion', quantityText: '1 medium' },
      { name: 'Crayfish (ground)', quantityText: '2 tbsp' },
      { name: 'Smoked Fish or Dried Fish', quantityText: '150g' },
      { name: 'Ugu leaves or Spinach', quantityText: 'Handful' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Salt', quantityText: 'To taste' },
    ],
    steps: [
      'Peel the yam and cut it into medium-sized cubes. Wash thoroughly until the water runs clear and set aside.',
      'Blend the tomatoes, red bell pepper, scotch bonnet, and half of the onion to a coarse paste.',
      'Heat the palm oil in a pot. Slice the remaining onion and fry for 2 minutes. Add the blended pepper mix and fry for 10 minutes until the oil floats to the top.',
      'Add the ground crayfish, smoked fish, crumbled seasoning cubes, and salt. Add enough water to just cover the yam cubes.',
      'Bring the sauce to a rolling boil, then add the yam cubes. Cover and cook on medium heat for 20-25 minutes until the yam is soft.',
      'Once soft, use a wooden spoon to gently mash about 30% of the yam cubes against the pot to thicken the porridge.',
      'Stir in the spinach or ugu leaves, simmer for 2 minutes, and remove from heat. Serve hot.',
    ],
  },
  {
    slug: 'pounded-yam',
    title: 'Traditional Pounded Yam',
    heroImage: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&h=800&fit=crop&q=85',
    cookTimeMin: 30,
    servings: 4,
    category: 'Nigerian',
    difficulty: 'Medium',
    description: 'The king of Nigerian swallows! Smooth, stretchy, and pillowy soft pounded yam made from scratch using fresh African puna yams. Best enjoyed with Egusi or Efo Riro.',
    ingredients: [
      { name: 'African Yam (Puna Yam)', quantityText: '1 large tuber' },
      { name: 'Water', quantityText: 'As needed for boiling' },
    ],
    steps: [
      'Peel the yam, slice it into round chunks, and wash thoroughly in cold water.',
      'Place the yam chunks in a pot, add enough water to completely submerge them, and bring to a boil.',
      'Cook on medium-high heat for 20-25 minutes until the yam is fork-tender. Do not drain the hot yam water yet!',
      'Transfer the hot yam chunks directly into a mortar. Using a pestle, pound vigorously and continuously.',
      'Pound until the yam breaks down completely, removing any lumps, and it becomes a smooth, stretchy dough. Add a splash of the hot yam water if it gets too tough.',
      'Form into neat rounds and serve immediately with your favorite soup.',
    ],
  },
  {
    slug: 'banku-and-tilapia',
    title: 'Banku and Grilled Tilapia',
    heroImage: 'https://images.unsplash.com/photo-1536304993881-ff86e0c9e8a6?w=1200&h=800&fit=crop&q=85',
    cookTimeMin: 45,
    servings: 4,
    category: 'Ghanaian',
    difficulty: 'Medium',
    description: 'A classic Ghanaian dish. Fermented corn and cassava dough cooked into a smooth, slightly sour dumpling, served alongside perfectly spiced and grilled Tilapia with fresh hot pepper sauce.',
    ingredients: [
      { name: 'Corn Dough (fermented)', quantityText: '2 cups' },
      { name: 'Cassava Dough', quantityText: '1 cup' },
      { name: 'Fresh Tilapia Fish', quantityText: '2 whole, cleaned' },
      { name: 'Ginger and Garlic Paste', quantityText: '2 tbsp' },
      { name: 'Scotch Bonnet Pepper', quantityText: '4 (for the sauce)' },
      { name: 'Fresh Tomatoes', quantityText: '3 (for the sauce)' },
      { name: 'Onion', quantityText: '2 (1 for marinade, 1 for sauce)' },
      { name: 'Seasoning Cubes', quantityText: '2' },
      { name: 'Salt', quantityText: 'To taste' },
      { name: 'Vegetable Oil', quantityText: '3 tbsp' },
    ],
    steps: [
      'Make the marinade for the fish: blend ginger, garlic, half an onion, salt, and seasoning. Make deep diagonal cuts in the cleaned tilapia and rub the marinade generously inside and out. Marinate for 30 mins.',
      'Grill the tilapia in an oven at 200°C or on an outdoor grill for 20-25 minutes, flipping halfway, until cooked through and slightly charred.',
      'Prepare the Banku: In a heavy pot, mix the corn dough and cassava dough with 2 cups of water. Stir continuously with a wooden spoon over medium heat.',
      'As it thickens, it will require vigorous stirring and kneading against the side of the pot to remove lumps. Add small splashes of water and cover to steam for 5 minutes. Form into smooth balls.',
      'Make the hot pepper sauce: coarsely grind or blend the fresh tomatoes, scotch bonnet, and remaining onion with a pinch of salt.',
      'Serve the hot Banku balls with the freshly grilled Tilapia and the raw hot pepper sauce on the side.',
    ],
  }
];

async function main() {
  console.log('Seeding 24 West African recipes...');

  let created = 0;
  for (const recipe of RECIPES) {
    const existing = await prisma.recipe.findUnique({ where: { slug: recipe.slug } });
    if (existing) {
      console.log(`  SKIP (exists): ${recipe.title}`);
      continue;
    }

    await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        body: recipe.description,
        heroImage: recipe.heroImage,
        cookTimeMin: recipe.cookTimeMin,
        servings: recipe.servings,
        isPublished: true,
        ingredients: {
          create: recipe.ingredients.map((ing) => ({
            name: ing.name,
            quantityText: ing.quantityText,
            sku: ing.sku ?? null,
          })),
        },
        steps: {
          create: recipe.steps.map((body, i) => ({
            position: i + 1,
            body,
          })),
        },
      },
    });

    console.log(`  ✓ ${recipe.title}`);
    created++;
  }

  console.log(`\nDone. Created ${created} / ${RECIPES.length} recipes.`);
  await prisma.$disconnect();
}

main().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
